[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "openai>=2.7.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "twilio>=9.8.5",
]
